# Generated by Django 2.0.4 on 2018-06-20 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, help_text='JPG, PNG 등 이미지 파일을 업로드해주세요', max_length=300, upload_to='upload_img', verbose_name='이미지'),
        ),
    ]
