# Generated by Django 2.0.4 on 2018-06-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180608_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, help_text='최대 300자 내외', max_length=300, null=True, verbose_name='내용'),
        ),
    ]
